semi: true
singleQuote: false
printWidth: 120
bracketSameLine: true

overrides:
  - files:
      - "*.html"
    options:
      parser: "jinja-template"
  - files:
      - "*.html"
      - "*.css"
      - "*.js"
    options:
      tabWidth: 4
